version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - revive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

  settings:
    revive:
      rules:
        - name: var-naming
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: blank-imports

formatters:
  enable:
    - gofmt
